### ISSUE TITLE
Cannot open overview result files (created in R 4.1.0 or greater)

### ISSUE THREAD

**Issue by jsnel** [glotaran/glotaran-legacy#40]
In R 4.1.0 the NLS output syntax was changed, which breaks the functionality of the overview file. 

Prior to R 4.1.0 NLS would print lines like e.g.:

> 0.02467975 : 1 0.2 -0.6931472 -2.995732 -4.60517 0.3 -0.1 0.01

And now:

> 0.02467975  (1.01e+00): par = (1 0.2 -0.6931472 -2.995732 -4.60517 0.3 -0.1 0.01)

This breaks the parsing in Glotaran in [AnalysisResultFileViewerTopComponent.java#L295-L326](https://github.com/glotaran/glotaran-legacy/blob/26aae8801701d4949942e31d6fe74549ea24a8d1/CoreResultDisplayers/src/main/java/org/glotaran/core/resultdisplayers/overview/AnalysisResultFileViewerTopComponent.java#L295-L326).

A workaround can be to only use Glotaran with R 4.0.5 or earlier, R 4.0.4 has been tested to work.
An older version of R can be downloaded [from here](https://cran.r-project.org/bin/windows/base/old/).

A fix for this issue would be to fix the parsing of the nlsprogress output in  AnalysisResultFileViewerTopComponent.

Stacktrace observed by the user:

```
java.util.NoSuchElementException
	at java.util.Scanner.throwFor(Scanner.java:862)
	at java.util.Scanner.next(Scanner.java:1371)
	at org.glotaran.core.resultdisplayers.overview.AnalysisResultFileViewerTopComponent.parseNlsProgress(AnalysisResultFileViewerTopComponent.java:310)
	at org.glotaran.core.resultdisplayers.overview.AnalysisResultFileViewerTopComponent.<init>(AnalysisResultFileViewerTopComponent.java:82)
	at org.glotaran.core.resultdisplayers.overview.AnalyisResultFileViewer.getCloneableTopComponent(AnalyisResultFileViewer.java:12)
	at org.glotaran.analysisoverviewfilesupport.AnalysisResultFileOpenSupport.createCloneableTopComponent(AnalysisResultFileOpenSupport.java:18)
```

The latest [R-news](https://cran.r-project.org/doc/manuals/r-release/NEWS.pdf) describes the change as:
![image](https://user-images.githubusercontent.com/3616369/126870862-406b698b-2737-4294-83a0-f35939c13724.png)

**Comment by jsnel** [comment]
This is an issue in Glotaran v1.5.1, it should be patched in v1.5.2 or later. Meanwhile the FAQ describes a workaround. Hopefully this will make it into google search results so people can easily find it.

**Comment by anhmel** [comment]
The problem with downgrading R version is that Glotaran v1.5.1 does not work with R 4.0.5 and earlier. Every time I try to run analysis it throws the same error both on Mac OS and Windows:
Test if R-package TIMP is installed: OK
Test if TIMP is up to date: OK.
Detected TIMP version: 1.13.2
Loading TIMP package: **FAIL**

**Comment by JWageM** [comment]
@anhmel What worked for me was:
R version 4.0.5
RTools 4.0
Install TIMP (from source) via: install.packages("Rserve", INSTALL_opts=c("—no-multiarch"))
Install RServe (from binary) via: install.packages("Rserve")

--- Running in R showed the following:
> library(TIMP)
> sessionInfo()
R version 4.0.5 (2021-03-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 26100)

Matrix products: default

locale:
[1] LC_COLLATE=English_Netherlands.1252 
[2] LC_CTYPE=English_Netherlands.1252   
[3] LC_MONETARY=English_Netherlands.1252
[4] LC_NUMERIC=C                        
[5] LC_TIME=English_Netherlands.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] TIMP_1.13.6        fields_17.1        RColorBrewer_1.1-3
[4] viridisLite_0.4.2  spam_2.11-3        Rserve_1.8-10     

loaded via a namespace (and not attached):
 [1] Rcpp_1.1.1         gtools_3.9.5       bitops_1.0-9      
 [4] grid_4.0.5         nnls_1.6           KernSmooth_2.23-18
 [7] gplots_3.3.0       splines_4.0.5      deSolve_1.40      
[10] tools_4.0.5        gclus_1.3.3        maps_3.4.3        
[13] compiler_4.0.5     colorspace_2.1-2   cluster_2.1.1     
[16] caTools_1.18.3     dotCall64_1.2      minpack.lm_1.2-4
